/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xs_ndkdemo_utils_JniUtil */

#ifndef _Included_com_xs_ndkdemo_utils_JniUtil
#define _Included_com_xs_ndkdemo_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xs_ndkdemo_utils_JniUtil
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xs_ndkdemo_utils_JniUtil_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_xs_ndkdemo_utils_JniUtil
 * Method:    getStringByboolean
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xs_ndkdemo_utils_JniUtil_getStringByboolean
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
